@AlertOpsBackend_HostAddress = http://localhost:5000

### GET all alerts
GET {{AlertOpsBackend_HostAddress}}/api/alerts
Accept: application/json

### GET alert stats
GET {{AlertOpsBackend_HostAddress}}/api/alerts/stats
Accept: application/json

### POST create alert
POST {{AlertOpsBackend_HostAddress}}/api/alerts
Content-Type: application/json

{
  "message": "High CPU Usage on web-01",
  "status": "Open",
  "severity": "Critical",
  "service": "web-01",
  "env": "Production",
  "time": "2 mins ago"
}

### GET all projects
GET {{AlertOpsBackend_HostAddress}}/api/projects
Accept: application/json

### GET all escalation rules
GET {{AlertOpsBackend_HostAddress}}/api/escalationrules
Accept: application/json
